
version: 0.0
os: linux

files:
  - source: /
    destination: /home/root/my-app1

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 600
      runas: root